version: '3.4'

services:
  postgres.data:
    restart: always
    environment:
      POSTGRES_PASSWORD: "admin"
    volumes:
      - postgresdata-volume:/var/lib/postgresql/data
    ports:
      - "55432:5432"
      
  db-adminer:
    image: adminer
    restart: always
    ports:
      - "28080:8080"
    depends_on:
      - postgres.data
      
  testprogrammationconformit:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ConformitDb=Host=postgres.data;Port=55432;Database=ConformitDb;Username=postgres;Password=admin

    ports:
      - "5001:80"

volumes:
  postgresdata-volume: